resolver: lts-14.23
packages:
- yamlparse-applicative
- yamlparse-applicative-demo
extra-deps:

- github: NorfairKing/validity
  commit: 0f52f3ba57d099f3d3ced38a2eeae39954906306
  subdirs:
  - validity
  - genvalidity
  - genvalidity-sydtest
- github: NorfairKing/safe-coloured-text
  commit: 61d959e65eeb6f4180d8ea4a0e2de1d5037b1394
  subdirs:
    - safe-coloured-text
- github: NorfairKing/sydtest
  commit: b51714b62418f5a2d57694a51cbf9bba1878a3be
  subdirs:
    - sydtest
    - sydtest-discover
- envparse-0.4.1@sha256:989902e6368532548f61de1fa245ad2b39176cddd8743b20071af519a709ce30,2842

nix:
  path: [ "nixpkgs=https://github.com/NixOS/nixpkgs/archive/323fe92057bb38475a446ff5e18d3b388c2e4403.tar.gz" ]
  add-gc-roots: true
  pure: true
  packages:
  - zlib
  - haskellPackages.hpack
