name:                yamlparse-applicative-demo
version:             0.0.0.0
github:              "NorfairKing/confparse"
license:             AllRightsReserved
author:              "Tom Sydney Kerckhove"
maintainer:          "syd@cs-syd.eu"
copyright:           "2020 Tom Sydney Kerckhove"


dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - aeson
  - containers
  - text
  - yamlparse-applicative
  - path

executables:
  yamlparse-applicative-demo:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - yamlparse-applicative-demo

tests:
  yamlparse-applicative-test:
    main: Spec.hs
    source-dirs: test
    build-tools: sydtest-discover
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - QuickCheck
    - aeson
    - containers
    - genvalidity-aeson
    - genvalidity-containers
    - genvalidity-scientific
    - genvalidity-sydtest
    - genvalidity-text
    - genvalidity-unordered-containers
    - path
    - scientific
    - sydtest
    - text
    - unordered-containers
    - vector
    - yamlparse-applicative
    - yamlparse-applicative-demo
