name:                yamlparse-applicative
version:             0.0.0.0
github:              "NorfairKing/confparse"
license:             AllRightsReserved
author:              "Tom Sydney Kerckhove"
maintainer:          "syd@cs-syd.eu"
copyright:           "2020 Tom Sydney Kerckhove"


dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - yaml
  - aeson
  - bytestring
  - text
  - prettyprinter
  - vector
  - unordered-containers

executables:
  yamlparse-applicative-demo:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - yamlparse-applicative

tests:
  yamlparse-applicative-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - yamlparse-applicative
