name:                yamlparse-applicative
version:             0.1.0.2
github:              "NorfairKing/yamlparse-applicative"
license:             MIT
author:              "Tom Sydney Kerckhove"
maintainer:          "syd@cs-syd.eu"
copyright:           "2020 Tom Sydney Kerckhove"
synopsis:            Declaritive configuration parsing with free docs
description:         See https://github.com/NorfairKing/yamlparse-applicative



dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - aeson
  - bytestring
  - containers
  - optparse-applicative
  - path
  - path-io
  - prettyprinter
  - safe-coloured-text
  - scientific
  - text
  - unordered-containers
  - validity
  - validity-text
  - vector
  - yaml
