name: "Nix Build"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v8
    - name: free disk space
      run: |
        sudo rm -rf /opt
    - uses: cachix/cachix-action@v6
      with:
        name: yamlparse
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: nix-build default.nix
    - run: nix-build ci.nix
